name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  { pattern = "vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "support.zoom.us.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "bakrie.ac.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "quiz.vidio.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "investor.fb.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "img.email2.vidio.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "app.gopay.co.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "www.uii.ac.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "untar.ac.id.vpn.stupidworld.web.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "387eff0217a64551a18d0703bd7c3fe2"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"

MAIN_PAGE_URL = "https://raw.githubusercontent.com/xyzsds/tx/refs/heads/main/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/xyzsds/tx/refs/heads/main/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/xyzsds/tx/refs/heads/main/link.html"
CONVERT_PAGE_URL = "https://raw.githubusercontent.com/xyzsds/tx/refs/heads/main/convert.html"
